services:
  vite:
    build:
      dockerfile: ./docker/Dockerfile-vite
    ports:
      - 5173:5173
    volumes:
      - ./assets:/app/assets/:cached # Location of the project for php-fpm. Note this should be the same for NGINX.*
    networks:
      - symfony
  fpm:
    build: # Info to build the Docker image
      dockerfile: ./docker/Dockerfile-php # Specify the name of the Dockerfile
    volumes:
      - ./:/var/www/project/:cached # Location of the project for php-fpm. Note this should be the same for NGINX.*
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.
  nginx:
    build:
      dockerfile: ./docker/Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 8000:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
      - symfony

networks:
  symfony:

volumes:
  persistent:
